AdminClient:
  conf:
    bootstrap.servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9092
    # debug: all
Consumer:
  bootstrap.servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9092
  group.id: dsv05
  default.topic.config:
    auto.offset.reset: smallest
  # debug: all
Topic:
  topics:
    - sru_jsonmarc_dsv05
Elastic:
  index: kafka-dsv05
  doc_type: record
  url: http://sb-ues2.swissbib.unibas.ch:9200
  timeout: 300
  mapping: null
