logging:
  # 10: debug, 20: info, 30: warning, 40:error
  level: 10
indexes:
  - index:
      index: kafka-dsv05-v7
      doc_type: record
      url: http://localhost:9200
  - index:
      index: kafka-dsv01-v7
      doc_type: record
      url: http://localhost:9200
