AdminClient:
  conf:
    bootstrap.servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9092
    debug: all
Producer:
  bootstrap.servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9092
  debug: all
Topic:
  topic: sru_jsonmarc_dsv05
  num_partitions: 1
  replication_factor: 1
SRU:
  database: defaultdb
  schema: marc/json
  max_records: 100