AdminClient:
  conf:
    bootstrap.servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9092
    # debug: all
Consumer:
  bootstrap.servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9092
  group.id: dsv05-v4
  default.topic.config:
    auto.offset.reset: smallest
  # debug: all
Topic:
  topics:
    - sru_jsonmarc_dsv05
Elastic:
  index: kafka-dsv05
  doc_type: record
  url: http://sb-ues2.swissbib.unibas.ch:9200
  timeout: 300
  mapping: null
DataTransformation:
  database: dsv05
  config:
    digidata:
      index: add-digidata
      doc_type: data
      url: http://sb-ues2.swissbib.unibas.ch:9200
      timeout: 300
      mapping: null
    opac:
      index: opac-access
      doc_type: log
      url: http://sb-ues2.swissbib.unibas.ch:9200
      timeout: 300
      mapping: null
    reservations:
      index: reservations
      doc_type: record
      url: http://sb-ues2.swissbib.unibas.ch:9200
      timeout: 300
      mapping: null
    swissbib.host: http://sb-uesl1.swissbib.unibas.ch:8080
    page-conversions:
      Partitur: 50
      Brief: 3
      Buch: 245
      Laufmeter: 8000
      Schachtel: 800
      Mappe: 80
      Briefmappe: 40