AdminClient:
  conf:
    bootstrap.servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9092
    # debug: all
Consumer:
  bootstrap.servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9092
  group.id: dsv05-v10
  default.topic.config:
    auto.offset.reset: smallest
  # debug: all
Topic:
  topics:
    - sru_jsonmarc_dsv05_v2
Elastic:
  index: kafka-dsv05-v7
  doc_type: record
  url: http://sb-ues2.swissbib.unibas.ch:9200
  timeout: 300
  mapping: null
DataTransformation:
  database: dsv05
  config:
    digidata:
      index: add-digidata
      doc_type: data
      url: http://sb-ues2.swissbib.unibas.ch:9200
      timeout: 300
      mapping: null
    page-conversions:
      Band: 245
      Artikel: 100

      # Musik
      Partitur: 50
      Stimmen: 25

      # Handschriften
      Manuskriptband: 245
      Faszikel: 45

      # Karten
      Karten: 4
      Kartenmappen: 40

      # Archiv
      Laufmeter: 8000
      # Formattyp Dossier: Dossier[s], Stück, Serie
      Archiveinheit: 80
      Schachteln: 800
      Mappen: 80

      # Briefe
      Briefe: 3
      Briefband: 80
      Briefmappen: 80

      # Bilder
      Fotomappen: 80

      # Zeitungen & Zeitschriften (total)
      Periodikum: 2000

