Kafka:
  host: sb-uka1.swissbib.unibas.ch:7078
  partition: 0
  topicToUse: DSV05
SRU:
  database: defaultdb
  schema: marc/json
  max_records: 100
  queries:
    - query:
        name: dc.id
        relation: =
        value: HAN*
