AdminClient:
  conf:
    bootstrap.servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9092
    # debug: all
Consumer:
  bootstrap.servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9092
  group.id: dsv01-v6
  default.topic.config:
    auto.offset.reset: smallest
  # debug: all
Topic:
  topics:
    - sru_jsonmarc_dsv01
Elastic:
  index: kafka-dsv01-v2
  doc_type: record
  url: http://sb-ues2.swissbib.unibas.ch:9200
  timeout: 300
  mapping: null
DataTransformation:
  database: dsv01
  config:
    digidata:
      index: add-digidata
      doc_type: data
      url: http://sb-ues2.swissbib.unibas.ch:9200
      timeout: 300
      mapping: null
    opac:
      index: opac-access
      doc_type: log
      url: http://sb-ues2.swissbib.unibas.ch:9200
      timeout: 300
      mapping: null
    reservations:
      index: reservations
      doc_type: record
      url: http://sb-ues2.swissbib.unibas.ch:9200
      timeout: 300
      mapping: null
    swissbib.host: http://sb-uesl1.swissbib.unibas.ch:8080
    page-conversions:
      Band: 245
      Artikel: 100

      # Musik
      Partitur: 50
      Stimmen: 25

      # Handschriften
      Manuskriptband: 245
      Faszikel: 45

      # Karten
      Karten: 4
      Kartenmappen: 40

      # Archiv
      Laufmeter: 8000
      # Formattyp Dossier: Dossier[s], Stück, Serie
      Archiveinheit: 80
      Schachteln: 800
      Mappen: 80

      # Briefe
      Briefe: 3
      Briefband: 80
      Briefmappen: 80

      # Bilder
      Fotomappen: 80



